### PR TITLE
Fix (#752) - Id disappearing bug

### LINKED ISSUE #752: bug: extra parameters in url are lost when data comes
## Bug Definition
I just clicked on the link while reviewing an issue. There was an id parameter in this link and the url was updated when the data came from the api. id value removed from url.

-- Please add discord contact information
** discord username: @ss.ibrahimbas#4990 **

## Bug environment
Describe the environment produces the bug. For example:
Both:
- rc.afetharita.com
- afetharita.com
## Describe how you are producing the bug step by step

1. Go to '[this link](https://afetharita.com/en?lat=36.936358468543396&lng=36.570053100585945&zoom=12&id=756628)'
2. look the url
3. &id field is going

## Expected Behaviour
id field is should stay in the url

## Screen shots
If possible, add screenshots to describe your bug.

## Desktop Information
- Operating System: [Windows 11]
- Browser [chrome]
- Version [for example 22]

## Additional Context
Not have additional context

### PR DESCRIPTION
**Pull request by cemiluzunhasan**
# Description
When the component is in stage of re-rendering, we're loosing ID parameter in route. This fix resolves related bug. 

**discord username: cemiluzunhasan#5776**

**closes #752 **

1. Add existing id parameter in mounted stage
2. Add existing id parameter in debouncing stage

## Things to check before creating a PR
- [X] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [X] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [X] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [X] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [X] Related file selection: Only relevant files should be touched and no other files should be affected.
- [X] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [X] Clean commit history: The commits where the changes are made should be clear and organized.
- [X] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change
- [X] Bug Fix

# How were these changes tested?
The component has been forced to re-render itself. Also debouncing condition has been applied to component.

**Test Configuration**:

* Firmware version:
* Hardware: Macbook 13 - Chrome Browser
* Toolchain:
* SDK:

### CODE REVIEW

**Review by Rayberk — APPROVED** [review]

File: components/UI/Map/LeafletMap.tsx [hunk 1]
```diff
@@ -65,21 +65,35 @@ const MapEvents = () => {
...
-      );
+      if (id) {
+        window.history.replaceState(
+          {
+            ...window.history.state,
+            as: localCoordinatesURL,
+            url: localCoordinatesURL,
+          },
+          "",
+          `?${localCoordinatesURL}&id=${id}`
```
Comment (oguzergul) [inline components/UI/Map/LeafletMap.tsx:84]: can you use terniary operator for this cases

File: components/UI/Map/LeafletMap.tsx [hunk 2]
```diff
@@ -65,21 +65,35 @@ const MapEvents = () => {
   const router = useRouter();
   const { setPopUpData, setEventType } = useMapActions();
   const { setCoordinates } = useURLActions();
+  const id = router.query["id"];
```
Comment (oguzergul) [inline components/UI/Map/LeafletMap.tsx:68]: you can use the next router for reaching router parameters.

**Review by oguzergul — CHANGES_REQUESTED** [review]

File: components/UI/Map/LeafletMap.tsx (hunk 2 above)
Comment (usirin) [reply components/UI/Map/LeafletMap.tsx:68]: this is already the next router

**Review by EmirBoyaci — APPROVED** [review]

**Review by usirin — APPROVED** [review]
