### PR TITLE
fix(#1006): Make `ScanAreaButton` work and create `areasStore` to prevent unnecessary renders

### LINKED ISSUE #1006: bug: Wrong remaining time implementation on `ScanAreaButton.tsx`
## Bug Definition

https://user-images.githubusercontent.com/22892227/218948710-7f5c02cd-bf0d-4f28-ba78-437f0a56f80f.mov

The problem comes from the line  22. When you mount a react hook in multiple files/components they'll have independent states.
Screenshot 2023-02-15 at 09 10 48

-- Please add discord contact information
** discord username: @puskuruk  **

## Bug environment
rc.afetharita.com

### PR DESCRIPTION
**Pull request by puskuruk**
# Description
`ScanAreaButton` wasn't working correctly and the old implementation causes unnecessary renders. As a solution created a new store and changed where we mount `useAreas` hook.

**discord username: @puskuruk **

**closes #1006**

Please describe your changes. Also describe your aim and content. Do not forget to list the dependencies required caused by those changes.

## Things to check before creating a PR
- [x] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [x] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [x] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [x] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [x] Related file selection: Only relevant files should be touched and no other files should be affected.
- [x] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [x] Clean commit history: The commits where the changes are made should be clear and organized.
- [x] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

File: src/hooks/useGetAreas.tsx [hunk 1]
```diff
@@ -1,35 +1,41 @@
...
+} from "@/stores/areasStore";
+import { dataFetcher } from "@/services/dataFetcher";
+import { DataLite } from "@/mocks/TypesAreasEndpoint";
+import { dataTransformerLite } from "@/utils/dataTransformer";
 
 export function useGetAreas() {
   const [sendRequest, setSendRequest] = useState(false);
-  const [shouldFetchNextOption, setShouldFetchNextOption] =
-    useState<boolean>(false);
+  useState<boolean>(false);
```
Comment (puskuruk) [inline src/hooks/useGetAreas.tsx:27]: Remove

Comment (puskuruk) [reply src/hooks/useGetAreas.tsx]: Done :beers:

**Review by usirin — APPROVED** [review]
