### PR TITLE
fix: on click every component on map layer it zoom in issue fixed

### LINKED ISSUE #1136: bug: Double click on every element results in zoom in
## Bug Definition
No matter where you click (be it a button, map type etc.) the page is zoomed in.

 discord username: Mustafa Aksu

## Bug environment

rc.afetharita.com

## Describe how you are producing the bug step by step

1. Go to rc.afetharita.com
2. Click a button TWICE (f.e : Scan button or literally anywhere on the page)

## Expected Behaviour
The page should NOT be zoomed in.

## Actual Behaviour
The page is zoomed in.

## Desktop Information
- Operating System : WINDOWS
- Browser : CHROME
- Version : latest

## Mobile Phone Information
- Devıce : [iPhone14
- Operating System (with the version): IOS v16.2
- Version :  SAFARI
- Browser Version :  latests

### PR DESCRIPTION
**Pull request by oguzergul**
# Description

**discord username: oguzergul#9634**

**closes #1136 **

Please describe your changes. Also describe your aim and content. Do not forget to list the dependencies required caused by those changes.

## Things to check before creating a PR
- [ ] I have inspected my topic, checked.
- [ ] If it is a core feature, executed detailed tests.

## Creating PR rules
- [ ] PR must be created for an issue with approved tag. Otherwise PR will be rejected.
- [ ] Relevant issue number: The issue number related to PR must be attached to head of PR header, after prefix after prefix # must be attached in parenthesis. A header like this could be used "prefix(#issue_number): PR header" .
- [ ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules. For example, a title like "docs(#issueId): Add README.md" can be used.
- [ ] Related file selection: Only relevant files should be touched and no other files should be affected.
- [ ] Format and Lint Suitability : The code should be made in accordance with a certain format standard and examined according to the lint rules.
- [ ] Clean commit history: The commits where the changes are made should be clear and organized.
- [ ] Opening PR when job is completed: PR should be opened when job is completed and sent for review by other team members.

## Changes

- [ ] A new feature (a change that adds a new feature, not a breaking change)
- [ ] A new refactor (a change that is not a breaking change, that improves the readability or performance of the code)
- [ ] A breaking change
- [ ] Documentation change

# How were these changes tested?

Please describe the tests you did to test the changes you made. Please also specify your test configuration.

**Test Configuration**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

File: src/newlayout/components/Map/Controls/index.tsx [hunk 1]
```diff
@@ -187,93 +188,98 @@ const MapControls = (props: IMapControlsProps) => {
...
-      <Control position="topright">
-        <Stack
-          display={"flex"}
-          direction={"column"}
-          rowGap={2}
-          alignItems={"flex-end"}
-        >
-          <Stack display={"flex"} direction={"row"} columnGap={2}>
-            {/* <FilterButtonComponent
+    <DoubleClickStopPropagation>
```
Comment (usirin) [inline src/newlayout/components/Map/Controls/index.tsx:191]: @oguzergul Isn't this the same as just passing a regular `onDoubleClick` handler to the div below? 🤔
